# Generated by Django 3.2.5 on 2021-09-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('father_name', models.CharField(default='', max_length=200)),
                ('mother_name', models.CharField(default='', max_length=200)),
                ('course_name', models.CharField(default='', max_length=50, verbose_name='students class/standard')),
                ('date_of_birth', models.DateTimeField(verbose_name='date of birth')),
                ('enrollment_date', models.DateTimeField()),
            ],
        ),
    ]
