# Generated by Django 3.2.5 on 2021-09-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('father_name', models.CharField(default='', max_length=200)),
                ('mother_name', models.CharField(default='', max_length=200)),
                ('course_name', models.CharField(default='', max_length=50, verbose_name='students class/standard')),
                ('date_of_birth', models.DateTimeField(verbose_name='date of birth')),
                ('enrollment_date', models.DateTimeField()),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_month', models.CharField(choices=[('Jan', 'Freshman'), ('Feb', 'Sophomore'), ('Mar', 'Junior'), ('Apr', 'Senior'), ('May', 'Graduate'), ('Jun', 'Graduate'), ('Jul', 'Graduate'), ('Aug', 'Graduate'), ('Sep', 'Graduate'), ('Oct', 'Graduate'), ('Nov', 'Graduate'), ('Dec', 'Graduate')], default='', max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='students.students', verbose_name='Students')),
            ],
        ),
    ]
