# Generated by Django 3.2.5 on 2021-09-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
