# Generated by Django 3.2.5 on 2021-09-05 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_month', models.CharField(choices=[('Jan', 'Freshman'), ('Feb', 'Sophomore'), ('Mar', 'Junior'), ('Apr', 'Senior'), ('May', 'Graduate'), ('Jun', 'Graduate'), ('Jul', 'Graduate'), ('Aug', 'Graduate'), ('Sep', 'Graduate'), ('Oct', 'Graduate'), ('Nov', 'Graduate'), ('Dec', 'Graduate')], default='', max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='students.students', verbose_name='Students')),
            ],
        ),
    ]
